import javax.swing.*;
import javax.swing.border.*;
import java.awt.*;
import java.awt.event.*;
import java.io.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

// ── ZERO external dependencies ────────────────────────────────────────────────
//    PDF is generated by hand-writing a minimal PDF 1.4 file using only
//    java.io — no iText, no Apache PDFBox, nothing to download.
// ─────────────────────────────────────────────────────────────────────────────

public class StudentGradeCalculator extends JFrame {

    // ── Student Info
    private JTextField nameField, idField;

    // ── Subject fields (5 subjects)
    private JTextField[] markFields   = new JTextField[5];
    private JTextField[] subjectNames = new JTextField[5];
    private JLabel[]     markErrors   = new JLabel[5];

    // ── Result labels
    private JLabel totalLabel, avgLabel, percentLabel, gradeLabel,
                   passFailLabel, remarksLabel;

    // ── State
    private boolean isDark     = false;
    private int[]   lastMarks  = new int[5];
    private boolean calculated = false;

    // ── Palette
    private static final Color LIGHT_BG   = new Color(245, 247, 250);
    private static final Color DARK_BG    = new Color(30, 30, 46);
    private static final Color ACCENT     = new Color(99, 102, 241);
    private static final Color CARD_LIGHT = Color.WHITE;
    private static final Color CARD_DARK  = new Color(49, 50, 68);
    private static final Color SUCCESS    = new Color(34, 197, 94);
    private static final Color WARN       = new Color(234, 179, 8);
    private static final Color DANGER     = new Color(239, 68, 68);

    // ─────────────────────────────────────────────────────────────────────
    public StudentGradeCalculator() {
        setTitle("Student Grade Calculator");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setMinimumSize(new Dimension(640, 750));

        JPanel root = new JPanel(new BorderLayout());
        root.setBackground(LIGHT_BG);
        root.add(buildHeader(),  BorderLayout.NORTH);
        root.add(buildCenter(),  BorderLayout.CENTER);
        root.add(buildButtons(), BorderLayout.SOUTH);

        setContentPane(root);
        pack();
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // ── Header
    private JPanel buildHeader() {
        JPanel p = new JPanel(new BorderLayout());
        p.setBackground(ACCENT);
        p.setBorder(new EmptyBorder(18, 24, 18, 24));

        JLabel title = new JLabel("Student Grade Calculator");
        title.setFont(new Font("SansSerif", Font.BOLD, 22));
        title.setForeground(Color.WHITE);

        JButton darkBtn = new JButton("Dark Mode");
        darkBtn.setFont(new Font("SansSerif", Font.PLAIN, 13));
        darkBtn.setFocusPainted(false);
        darkBtn.setBorderPainted(false);
        darkBtn.setBackground(ACCENT);
        darkBtn.setForeground(Color.WHITE);
        darkBtn.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        darkBtn.addActionListener(e -> toggleDarkMode());

        p.add(title,   BorderLayout.WEST);
        p.add(darkBtn, BorderLayout.EAST);
        return p;
    }

    // ── Scrollable centre
    private JScrollPane buildCenter() {
        JPanel inner = new JPanel();
        inner.setLayout(new BoxLayout(inner, BoxLayout.Y_AXIS));
        inner.setBackground(LIGHT_BG);
        inner.setBorder(new EmptyBorder(16, 20, 16, 20));

        inner.add(buildCard("Student Information", buildStudentPanel()));
        inner.add(Box.createVerticalStrut(12));
        inner.add(buildCard("Subject Marks  (out of 100 each)", buildSubjectsPanel()));
        inner.add(Box.createVerticalStrut(12));
        inner.add(buildResultCard());

        JScrollPane sp = new JScrollPane(inner);
        sp.setBorder(BorderFactory.createEmptyBorder());
        sp.getVerticalScrollBar().setUnitIncrement(16);
        return sp;
    }

    private JPanel buildCard(String heading, JPanel content) {
        JPanel card = new JPanel(new BorderLayout(0, 8));
        card.setBackground(CARD_LIGHT);
        card.setBorder(new CompoundBorder(
            new LineBorder(new Color(220, 220, 230), 1, true),
            new EmptyBorder(14, 16, 14, 16)
        ));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        JLabel h = new JLabel(heading);
        h.setFont(new Font("SansSerif", Font.BOLD, 14));
        h.setForeground(new Color(80, 80, 120));
        card.add(h, BorderLayout.NORTH);
        card.add(content, BorderLayout.CENTER);
        return card;
    }

    private JPanel buildStudentPanel() {
        JPanel p = new JPanel(new GridLayout(2, 2, 10, 8));
        p.setBackground(CARD_LIGHT);
        p.setBorder(new EmptyBorder(8, 0, 0, 0));

        p.add(label("Student Name:"));
        nameField = styledField("e.g. Arun Kumar");
        p.add(nameField);

        p.add(label("Student ID / Roll No:"));
        idField = styledField("e.g. 2024CS001");
        p.add(idField);
        return p;
    }

    private JPanel buildSubjectsPanel() {
        String[] defaults = {"Tamil", "English", "Mathematics", "Science", "Social Science"};
        JPanel grid = new JPanel(new GridBagLayout());
        grid.setBackground(CARD_LIGHT);
        grid.setBorder(new EmptyBorder(8, 0, 0, 0));

        GridBagConstraints gc = new GridBagConstraints();
        gc.insets = new Insets(4, 4, 4, 4);
        gc.fill   = GridBagConstraints.HORIZONTAL;

        gc.gridy = 0; gc.gridx = 0; gc.weightx = 0.6;  grid.add(boldLabel("Subject Name"), gc);
        gc.gridx = 1; gc.weightx = 0.25;                grid.add(boldLabel("Marks (0-100)"), gc);
        gc.gridx = 2; gc.weightx = 0.15;                grid.add(boldLabel(""), gc);

        for (int i = 0; i < 5; i++) {
            gc.gridy = i + 1;

            subjectNames[i] = styledField(defaults[i]);
            subjectNames[i].setText(defaults[i]);
            gc.gridx = 0; gc.weightx = 0.6;
            grid.add(subjectNames[i], gc);

            markFields[i] = styledField("0-100");
            final int idx = i;
            markFields[i].addFocusListener(new FocusAdapter() {
                public void focusLost(FocusEvent e) { validateMark(idx); }
            });
            gc.gridx = 1; gc.weightx = 0.25;
            grid.add(markFields[i], gc);

            markErrors[i] = new JLabel(" ");
            markErrors[i].setFont(new Font("SansSerif", Font.PLAIN, 11));
            markErrors[i].setForeground(DANGER);
            gc.gridx = 2; gc.weightx = 0.15;
            grid.add(markErrors[i], gc);
        }
        return grid;
    }

    private JPanel buildResultCard() {
        JPanel card = new JPanel(new BorderLayout(0, 8));
        card.setBackground(CARD_LIGHT);
        card.setBorder(new CompoundBorder(
            new LineBorder(new Color(220, 220, 230), 1, true),
            new EmptyBorder(14, 16, 14, 16)
        ));
        card.setMaximumSize(new Dimension(Integer.MAX_VALUE, Integer.MAX_VALUE));

        JLabel h = new JLabel("Results");
        h.setFont(new Font("SansSerif", Font.BOLD, 14));
        h.setForeground(new Color(80, 80, 120));
        card.add(h, BorderLayout.NORTH);

        JPanel grid = new JPanel(new GridLayout(2, 3, 12, 10));
        grid.setBackground(CARD_LIGHT);
        grid.setBorder(new EmptyBorder(8, 0, 0, 0));

        totalLabel    = resultLabel("Total: -");
        avgLabel      = resultLabel("Average: -");
        percentLabel  = resultLabel("Percentage: -");
        gradeLabel    = resultLabel("Grade: -");
        passFailLabel = resultLabel("Status: -");
        remarksLabel  = resultLabel("Remarks: -");

        grid.add(totalLabel);
        grid.add(avgLabel);
        grid.add(percentLabel);
        grid.add(gradeLabel);
        grid.add(passFailLabel);
        grid.add(remarksLabel);

        card.add(grid, BorderLayout.CENTER);
        return card;
    }

    private JPanel buildButtons() {
        JPanel p = new JPanel(new FlowLayout(FlowLayout.CENTER, 12, 12));
        p.setBackground(LIGHT_BG);
        p.setBorder(new MatteBorder(1, 0, 0, 0, new Color(220, 220, 230)));

        p.add(actionBtn("Calculate",  ACCENT,                   e -> calculate()));
        p.add(actionBtn("Reset",      new Color(107, 114, 128), e -> reset()));
        p.add(actionBtn("Save TXT",   new Color(16, 185, 129),  e -> saveFile()));
        p.add(actionBtn("Export PDF", new Color(220, 60, 60),   e -> exportPDF()));
        return p;
    }

    // ── UI helpers
    private JLabel label(String t) {
        JLabel l = new JLabel(t);
        l.setFont(new Font("SansSerif", Font.PLAIN, 13));
        return l;
    }
    private JLabel boldLabel(String t) {
        JLabel l = new JLabel(t);
        l.setFont(new Font("SansSerif", Font.BOLD, 13));
        return l;
    }
    private JLabel resultLabel(String t) {
        JLabel l = new JLabel(t);
        l.setFont(new Font("SansSerif", Font.BOLD, 13));
        l.setForeground(new Color(60, 60, 90));
        return l;
    }
    private JTextField styledField(String tip) {
        JTextField f = new JTextField();
        f.setFont(new Font("SansSerif", Font.PLAIN, 13));
        f.setBackground(new Color(248, 249, 252));
        f.setBorder(new CompoundBorder(
            new LineBorder(new Color(200, 200, 215), 1, true),
            new EmptyBorder(5, 8, 5, 8)
        ));
        f.setToolTipText(tip);
        return f;
    }
    private JButton actionBtn(String text, Color bg, ActionListener al) {
        JButton b = new JButton(text);
        b.setFont(new Font("SansSerif", Font.BOLD, 13));
        b.setBackground(bg);
        b.setForeground(Color.WHITE);
        b.setFocusPainted(false);
        b.setBorderPainted(false);
        b.setOpaque(true);
        b.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        b.setBorder(new EmptyBorder(10, 20, 10, 20));
        b.addActionListener(al);
        b.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent e) { b.setBackground(bg.darker()); }
            public void mouseExited (MouseEvent e) { b.setBackground(bg); }
        });
        return b;
    }

    // ── Validation
    private boolean validateMark(int i) {
        String txt = markFields[i].getText().trim();
        try {
            int v = Integer.parseInt(txt);
            if (v < 0 || v > 100) throw new NumberFormatException();
            markErrors[i].setText(" ");
            markFields[i].setBackground(new Color(240, 255, 245));
            return true;
        } catch (NumberFormatException ex) {
            markErrors[i].setText(txt.isEmpty() ? "Required" : "0-100 only");
            markFields[i].setBackground(new Color(255, 240, 240));
            return false;
        }
    }

    // ── Calculate
    private void calculate() {
        boolean valid = true;
        for (int i = 0; i < 5; i++) if (!validateMark(i)) valid = false;
        if (!valid) {
            JOptionPane.showMessageDialog(this,
                "Please fix the highlighted errors first.",
                "Validation Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int total = 0, failed = 0;
        for (int i = 0; i < 5; i++) {
            lastMarks[i] = Integer.parseInt(markFields[i].getText().trim());
            total += lastMarks[i];
            if (lastMarks[i] < 35) failed++;
        }

        double avg     = total / 5.0;
        double percent = (total / 500.0) * 100;
        boolean pass   = (failed == 0);

        String grade, remarks;
        Color  gradeColor;
        if (!pass) {
            grade = "Fail";              gradeColor = DANGER;
            remarks = failed + " subject(s) below pass mark (35)";
        } else if (avg >= 90) {
            grade = "O (Outstanding)";   gradeColor = new Color(16, 185, 129);
            remarks = "Exceptional performance!";
        } else if (avg >= 75) {
            grade = "A+";                gradeColor = SUCCESS;
            remarks = "Excellent work!";
        } else if (avg >= 60) {
            grade = "A";                 gradeColor = SUCCESS;
            remarks = "Very good performance.";
        } else if (avg >= 50) {
            grade = "B+";                gradeColor = WARN;
            remarks = "Good - keep it up!";
        } else if (avg >= 40) {
            grade = "B";                 gradeColor = WARN;
            remarks = "Satisfactory.";
        } else {
            grade = "C";                 gradeColor = new Color(249, 115, 22);
            remarks = "Needs improvement.";
        }

        totalLabel   .setText("Total: "      + total + " / 500");
        avgLabel     .setText("Average: "    + String.format("%.2f", avg));
        percentLabel .setText("Percentage: " + String.format("%.2f", percent) + "%");
        gradeLabel   .setText("Grade: "      + grade);
        gradeLabel   .setForeground(gradeColor);
        passFailLabel.setText("Status: "     + (pass ? "PASS" : "FAIL"));
        passFailLabel.setForeground(pass ? SUCCESS : DANGER);
        remarksLabel .setText("Remarks: "    + remarks);

        calculated = true;
        Toolkit.getDefaultToolkit().beep();
    }

    // ── Reset
    private void reset() {
        nameField.setText(""); idField.setText("");
        for (int i = 0; i < 5; i++) {
            markFields[i].setText("");
            markFields[i].setBackground(new Color(248, 249, 252));
            markErrors[i].setText(" ");
        }
        Color def = new Color(60, 60, 90);
        totalLabel   .setText("Total: -");
        avgLabel     .setText("Average: -");
        percentLabel .setText("Percentage: -");
        gradeLabel   .setText("Grade: -");    gradeLabel   .setForeground(def);
        passFailLabel.setText("Status: -");   passFailLabel.setForeground(def);
        remarksLabel .setText("Remarks: -");
        calculated = false;
    }

    // ── Dark mode
    private void toggleDarkMode() {
        isDark = !isDark;
        applyTheme(getContentPane(),
            isDark ? DARK_BG   : LIGHT_BG,
            isDark ? CARD_DARK : CARD_LIGHT,
            isDark ? new Color(220, 220, 240) : new Color(30, 30, 60));
        repaint();
    }
    private void applyTheme(Container c, Color bg, Color card, Color fg) {
        for (Component comp : c.getComponents()) {
            if (comp instanceof JPanel) {
                JPanel pnl = (JPanel) comp;
                pnl.setBackground(
                    pnl.getBorder() instanceof CompoundBorder ? card : bg);
                applyTheme(pnl, bg, card, fg);
            } else if (comp instanceof JLabel) {
                JLabel l = (JLabel) comp;
                Color cur = l.getForeground();
                if (cur.equals(new Color(60, 60, 90))
                        || cur.equals(new Color(80, 80, 120))
                        || cur.equals(Color.BLACK))
                    l.setForeground(fg);
            } else if (comp instanceof JTextField) {
                comp.setBackground(isDark ? new Color(60, 60, 80) : new Color(248, 249, 252));
                comp.setForeground(fg);
            } else if (comp instanceof JScrollPane) {
                comp.setBackground(bg);
                applyTheme((Container) comp, bg, card, fg);
            }
        }
    }

    // ── Save TXT
    private void saveFile() {
        if (!calculated) { alert("Please calculate first."); return; }
        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File("grade_result.txt"));
        if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;
        try (FileWriter fw = new FileWriter(fc.getSelectedFile())) {
            fw.write(buildReportText());
            JOptionPane.showMessageDialog(this,
                "Saved: " + fc.getSelectedFile().getName(),
                "Saved", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            alert("Error saving: " + e.getMessage());
        }
    }

    private String buildReportText() {
        String ts = LocalDateTime.now()
            .format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));
        StringBuilder sb = new StringBuilder();
        sb.append("========================================\n");
        sb.append("       STUDENT GRADE REPORT\n");
        sb.append("========================================\n");
        sb.append("Date/Time : ").append(ts).append("\n");
        sb.append("Name      : ").append(nameField.getText().trim().isEmpty() ? "N/A" : nameField.getText().trim()).append("\n");
        sb.append("ID        : ").append(idField  .getText().trim().isEmpty() ? "N/A" : idField  .getText().trim()).append("\n");
        sb.append("----------------------------------------\n");
        sb.append(String.format("%-24s %s%n", "SUBJECT", "MARKS"));
        sb.append("----------------------------------------\n");
        for (int i = 0; i < 5; i++) {
            String sn = subjectNames[i].getText().trim().isEmpty()
                ? "Subject " + (i + 1) : subjectNames[i].getText().trim();
            sb.append(String.format("%-24s %d%n", sn, lastMarks[i]));
        }
        sb.append("----------------------------------------\n");
        sb.append(totalLabel   .getText()).append("\n");
        sb.append(avgLabel     .getText()).append("\n");
        sb.append(percentLabel .getText()).append("\n");
        sb.append(gradeLabel   .getText()).append("\n");
        sb.append(passFailLabel.getText()).append("\n");
        sb.append(remarksLabel .getText()).append("\n");
        sb.append("========================================\n");
        return sb.toString();
    }

    // ── Export PDF (pure Java, zero external libraries) ───────────────────
    private void exportPDF() {
        if (!calculated) { alert("Please calculate first."); return; }

        JFileChooser fc = new JFileChooser();
        fc.setSelectedFile(new File("grade_report.pdf"));
        if (fc.showSaveDialog(this) != JFileChooser.APPROVE_OPTION) return;

        File outFile = fc.getSelectedFile();
        if (!outFile.getName().toLowerCase().endsWith(".pdf"))
            outFile = new File(outFile.getAbsolutePath() + ".pdf");

        try {
            String ts   = LocalDateTime.now().format(DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss"));
            String name = nameField.getText().trim().isEmpty() ? "N/A" : nameField.getText().trim();
            String id   = idField  .getText().trim().isEmpty() ? "N/A" : idField  .getText().trim();
            writePdf(outFile, ts, name, id);
            JOptionPane.showMessageDialog(this,
                "PDF saved:\n" + outFile.getAbsolutePath(),
                "Success", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            alert("PDF Error: " + ex.getMessage());
        }
    }

    // ── Minimal hand-written PDF 1.4 (no external library) ───────────────
    private void writePdf(File file, String ts, String name, String id)
            throws IOException {

        // A4 page in points (1 pt = 1/72 inch)
        final int W = 595, H = 842;

        // Build the content stream
        StringBuilder cs = new StringBuilder();
        int y = H - 60;   // current Y (PDF origin = bottom-left)

        // Title
        cs.append("BT /F1 20 Tf ");
        cs.append("0.388 0.4 0.945 rg ");
        int titleX = (W - (int)("Student Grade Report".length() * 10)) / 2;
        cs.append(titleX).append(" ").append(y).append(" Td ");
        cs.append("(Student Grade Report) Tj ET\n");
        cs.append("0 0 0 rg\n");
        y -= 36;

        // Meta lines
        y = addTextLine(cs, "Date : " + ts,   60, y, 11); y -= 4;
        y = addTextLine(cs, "Name : " + name, 60, y, 11); y -= 4;
        y = addTextLine(cs, "ID   : " + id,   60, y, 11); y -= 12;

        // Divider
        cs.append("0.7 0.7 0.85 rg ").append(60).append(" ").append(y)
          .append(" ").append(W - 120).append(" 1.5 re f\n0 0 0 rg\n");
        y -= 20;

        // Column headers
        cs.append("BT /F1 12 Tf 0.388 0.4 0.945 rg ");
        cs.append(60).append(" ").append(y).append(" Td (Subject) Tj ET\n");
        cs.append("BT /F1 12 Tf 0.388 0.4 0.945 rg ");
        cs.append(W - 130).append(" ").append(y).append(" Td (Marks) Tj ET\n");
        cs.append("0 0 0 rg\n");
        y -= 6;
        cs.append("0.7 0.7 0.85 rg ").append(60).append(" ").append(y)
          .append(" ").append(W - 120).append(" 1 re f\n0 0 0 rg\n");
        y -= 18;

        // Subject rows
        for (int i = 0; i < 5; i++) {
            String sn = subjectNames[i].getText().trim().isEmpty()
                ? "Subject " + (i + 1) : subjectNames[i].getText().trim();
            // Alternate row background
            if (i % 2 == 0) {
                cs.append("0.95 0.95 0.98 rg ");
                cs.append(58).append(" ").append(y - 4)
                  .append(" ").append(W - 116).append(" 20 re f\n0 0 0 rg\n");
            }
            y = addTextLine(cs, escapePdf(sn),          62, y, 11);
            // Mark — red if failed
            if (lastMarks[i] < 35) {
                cs.append("0.937 0.267 0.267 rg\n");
                addTextLine(cs, lastMarks[i] + " (F)", W - 130, y + 14, 11);
                cs.append("0 0 0 rg\n");
            } else {
                addTextLine(cs, String.valueOf(lastMarks[i]), W - 130, y + 14, 11);
            }
            y -= 4;
        }

        y -= 14;
        cs.append("0.7 0.7 0.85 rg ").append(60).append(" ").append(y)
          .append(" ").append(W - 120).append(" 1.5 re f\n0 0 0 rg\n");
        y -= 24;

        // Results table
        String[][] results = {
            { "Total",      totalLabel   .getText().replace("Total: ", "") },
            { "Average",    avgLabel     .getText().replace("Average: ", "") },
            { "Percentage", percentLabel .getText().replace("Percentage: ", "") },
            { "Grade",      gradeLabel   .getText().replace("Grade: ", "") },
            { "Status",     passFailLabel.getText().replace("Status: ", "") },
            { "Remarks",    remarksLabel .getText().replace("Remarks: ", "") },
        };
        for (String[] row : results) {
            // Key cell (shaded)
            cs.append("0.92 0.92 0.97 rg ");
            cs.append(58).append(" ").append(y - 5)
              .append(" 170 22 re f\n0 0 0 rg\n");
            addTextLine(cs, row[0], 62, y, 12);
            addTextLine(cs, escapePdf(row[1]), 245, y, 12);
            y -= 26;
        }

        // Footer
        y -= 16;
        cs.append("0.55 0.55 0.55 rg\n");
        addTextLine(cs, "Generated by Student Grade Calculator  |  " + ts, 60, y, 8);
        cs.append("0 0 0 rg\n");

        // ── Assemble raw PDF bytes ────────────────────────────────────────
        byte[] streamBytes = cs.toString().getBytes("ISO-8859-1");

        ByteArrayOutputStream buf = new ByteArrayOutputStream(8192);
        int[] off = new int[6];  // byte offsets for objects 1-5

        writePdfStr(buf, "%PDF-1.4\n%\u00e2\u00e3\u00cf\u00d3\n");

        off[1] = buf.size();
        writePdfStr(buf, "1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n");

        off[2] = buf.size();
        writePdfStr(buf, "2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n");

        off[3] = buf.size();
        writePdfStr(buf, "3 0 obj\n"
            + "<< /Type /Page /Parent 2 0 R\n"
            + "   /MediaBox [0 0 " + W + " " + H + "]\n"
            + "   /Contents 5 0 R\n"
            + "   /Resources << /Font << /F1 4 0 R >> >> >>\n"
            + "endobj\n");

        off[4] = buf.size();
        writePdfStr(buf, "4 0 obj\n"
            + "<< /Type /Font /Subtype /Type1\n"
            + "   /BaseFont /Helvetica\n"
            + "   /Encoding /WinAnsiEncoding >>\n"
            + "endobj\n");

        off[5] = buf.size();
        writePdfStr(buf, "5 0 obj\n<< /Length " + streamBytes.length + " >>\nstream\n");
        buf.write(streamBytes);
        writePdfStr(buf, "\nendstream\nendobj\n");

        int xrefOff = buf.size();
        writePdfStr(buf, "xref\n0 6\n");
        writePdfStr(buf, "0000000000 65535 f \n");
        for (int i = 1; i <= 5; i++)
            writePdfStr(buf, String.format("%010d 00000 n \n", off[i]));
        writePdfStr(buf, "trailer\n<< /Size 6 /Root 1 0 R >>\n");
        writePdfStr(buf, "startxref\n" + xrefOff + "\n%%EOF\n");

        try (FileOutputStream fos = new FileOutputStream(file)) {
            buf.writeTo(fos);
        }
    }

    /** Append a BT...ET text block and return (y - lineHeight) */
    private int addTextLine(StringBuilder cs, String text, int x, int y, int size) {
        cs.append("BT /F1 ").append(size).append(" Tf ")
          .append(x).append(" ").append(y).append(" Td ")
          .append("(").append(escapePdf(text)).append(") Tj ET\n");
        return y - (size + 4);
    }

    private void writePdfStr(ByteArrayOutputStream b, String s) throws IOException {
        b.write(s.getBytes("ISO-8859-1"));
    }

    private String escapePdf(String s) {
        return s.replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)")
                .replace("\r", "").replace("\n", " ");
    }

    private void alert(String msg) {
        JOptionPane.showMessageDialog(this, msg, "Info", JOptionPane.WARNING_MESSAGE);
    }

    // ── Main
    public static void main(String[] args) {
        try { UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName()); }
        catch (Exception ignored) {}
        SwingUtilities.invokeLater(StudentGradeCalculator::new);
    }
}
